/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2026 Alex Fishman <alex@fuse-t.org>
 */

#ifndef _SCORPI_IMAGE_SCO_FORMAT_H_
#define	_SCORPI_IMAGE_SCO_FORMAT_H_

#define	SCO_MAGIC			"SCOIMG\0\0"
#define	SCO_MAGIC_SIZE			8
#define	SCO_FORMAT_MAJOR		2
#define	SCO_FILE_ID_OFFSET		0x00000000ULL
#define	SCO_FILE_ID_SIZE		0x00001000U
#define	SCO_SUPERBLOCK_A_OFFSET		0x00001000ULL
#define	SCO_SUPERBLOCK_B_OFFSET		0x00002000ULL
#define	SCO_SUPERBLOCK_SIZE		0x00001000U
#define	SCO_METADATA_AREA_OFFSET		0x00010000ULL
#define	SCO_METADATA_PAGE_SIZE		0x00001000U
#define	SCO_MIN_FILE_SIZE		0x00010000ULL
#define	SCO_MIN_CLUSTER_SIZE		0x00010000U
#define	SCO_MAX_CLUSTER_SIZE		0x00400000U
#define	SCO_BASE_DESCRIPTOR_MIN_SIZE	0x00000050U
#define	SCO_CHECKSUM_CRC32C		1
#define	SCO_TABLE_SLOT_SIZE		16
#define	SCO_TABLE_SLOTS_PER_ENTRY	2
#define	SCO_TABLE_ENTRY_SIZE \
	(SCO_TABLE_SLOT_SIZE * SCO_TABLE_SLOTS_PER_ENTRY)
#define	SCO_MAX_SINGLE_TABLE_BYTES	(32ULL * 1024ULL * 1024ULL)

#define	SCO_INCOMPAT_FIXED_TABLE_V2	(1U << 0)
#define	SCO_INCOMPAT_SUPPORTED		SCO_INCOMPAT_FIXED_TABLE_V2
#define	SCO_RO_COMPAT_SEALED		(1U << 0)
#define	SCO_RO_COMPAT_SUPPORTED		SCO_RO_COMPAT_SEALED
#define	SCO_COMPAT_IMAGE_DIGEST		(1U << 0)
#define	SCO_COMPAT_SUPPORTED		SCO_COMPAT_IMAGE_DIGEST

#define	SCO_MAP_STATE_ABSENT		0
#define	SCO_MAP_STATE_PRESENT		1
#define	SCO_MAP_STATE_ZERO		2
#define	SCO_MAP_STATE_DISCARDED		3

#endif /* _SCORPI_IMAGE_SCO_FORMAT_H_ */
