/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2026 Alex Fishman <alex@fuse-t.org>
 */

#ifndef _SCORPI_IMAGE_SCO_FORMAT_H_
#define	_SCORPI_IMAGE_SCO_FORMAT_H_

#define	SCO_MAGIC			"SCOIMG\0\0"
#define	SCO_MAGIC_SIZE			8
#define	SCO_FORMAT_MAJOR		1
#define	SCO_FILE_ID_OFFSET		0x00000000ULL
#define	SCO_FILE_ID_SIZE		0x00001000U
#define	SCO_SUPERBLOCK_A_OFFSET		0x00001000ULL
#define	SCO_SUPERBLOCK_B_OFFSET		0x00002000ULL
#define	SCO_SUPERBLOCK_SIZE		0x00001000U
#define	SCO_METADATA_AREA_OFFSET		0x00010000ULL
#define	SCO_METADATA_PAGE_SIZE		0x00001000U
#define	SCO_MIN_FILE_SIZE		0x00010000ULL
#define	SCO_MIN_CLUSTER_SIZE		0x00010000U
#define	SCO_MAX_CLUSTER_SIZE		0x00400000U
#define	SCO_BASE_DESCRIPTOR_MIN_SIZE	0x00000050U
#define	SCO_CHECKSUM_CRC32C		1
#define	SCO_MAP_ENTRY_SIZE		16
#define	SCO_MAP_PAGE_HEADER_SIZE		0x00000018U
#define	SCO_MAP_ENTRIES_PER_PAGE \
	((SCO_METADATA_PAGE_SIZE - SCO_MAP_PAGE_HEADER_SIZE) / \
	SCO_MAP_ENTRY_SIZE)

#define	SCO_INCOMPAT_ALLOC_MAP_V1	(1U << 0)
#define	SCO_INCOMPAT_ZERO_DISCARD	(1U << 1)
#define	SCO_INCOMPAT_SUPPORTED \
	(SCO_INCOMPAT_ALLOC_MAP_V1 | SCO_INCOMPAT_ZERO_DISCARD)
#define	SCO_RO_COMPAT_SEALED		(1U << 0)
#define	SCO_RO_COMPAT_SUPPORTED		SCO_RO_COMPAT_SEALED
#define	SCO_COMPAT_IMAGE_DIGEST		(1U << 0)
#define	SCO_COMPAT_SUPPORTED		SCO_COMPAT_IMAGE_DIGEST

#define	SCO_MAP_STATE_ABSENT		0
#define	SCO_MAP_STATE_PRESENT		1
#define	SCO_MAP_STATE_ZERO		2
#define	SCO_MAP_STATE_DISCARDED		3

#endif /* _SCORPI_IMAGE_SCO_FORMAT_H_ */
